# CyberKali keybinds

bind = $mod, Return, exec, $terminal
bind = $mod, Space, exec, ags request launcher --instance cyberkali
bind = $mod, Q, killactive,
bind = $mod, F, togglefloating,
bind = $mod SHIFT, F, fullscreen, 0
bind = $mod, E, exec, $fileManager

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, down, movewindow, d

bind = $mod, 1, exec, ~/.config/cyberkali/bin/workspace-switch 1
bind = $mod, 2, exec, ~/.config/cyberkali/bin/workspace-switch 2
bind = $mod, 3, exec, ~/.config/cyberkali/bin/workspace-switch 3
bind = $mod, 4, exec, ~/.config/cyberkali/bin/workspace-switch 4
bind = $mod, 5, exec, ~/.config/cyberkali/bin/workspace-switch 5
bind = $mod, 6, exec, ~/.config/cyberkali/bin/workspace-switch 6
bind = $mod, 7, exec, ~/.config/cyberkali/bin/workspace-switch 7
bind = $mod, 8, exec, ~/.config/cyberkali/bin/workspace-switch 8
bind = $mod, 9, exec, ~/.config/cyberkali/bin/workspace-switch 9
bind = $mod, 0, exec, ~/.config/cyberkali/bin/workspace-switch 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# CyberKali shell overlays
bind = $mod SHIFT, N, exec, ags request netwatch --instance cyberkali
bind = $mod SHIFT, O, exec, ags request media --instance cyberkali
bind = $mod SHIFT, M, exec, ags request notifications --instance cyberkali
bind = $mod SHIFT, V, exec, ags request controls --instance cyberkali
bind = $mod SHIFT, P, exec, ags request power --instance cyberkali
bind = $mod SHIFT, Z, exec, ags request hud-layer --instance cyberkali
bind = $mod SHIFT, C, exec, cyberkali cycle
bind = $mod SHIFT, L, exec, ~/.config/cyberkali/bin/generate-lockscreen && hyprlock

# Capture
bind = $mod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mod SHIFT, R, exec, ~/.config/cyberkali/bin/toggle-recording

bind = $mod SHIFT, H, exec, notify-send 'CyberKali' 'SPACE launcher | SHIFT+N NetWatch | SHIFT+O Radioport | SHIFT+M Messages | SHIFT+V Controls | SHIFT+P Power | SHIFT+Z HUD layer | SHIFT+C flavors | SHIFT+L lock'

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
